# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
     - id: detect-secrets
       args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.1
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: ["commit-msg"]
        additional_dependencies:
          - "@commitlint/config-conventional"
  - repo: local
    hooks:
      - id: nomad-validate
        name: Nomad Validate
        entry: nomad validate
        language: system
        files: ^.*\.nomad
      - id: nomad-fmt
        name: Nomad Format
        entry: nomad fmt
        language: system
        files: ^.*\.nomad
      - id: packer-fmt
        name: Packer fmt
        entry: packer fmt
        language: system
        files: ^.*.pkr.hcl
      - id: packer-validate
        name: Packer validate
        entry: packer validate
        language: system
        files: ^.*.pkr.hcl

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    For more information, see https://pre-commit.ci
  autofix_prs: true
  skip:
    - nomad-validate
    - nomad-fmt
    - packer-validate
    - packer-fmt
