---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install -g "@semantic-release" "@semantic-release/github" "@semantic-release/commit-analyzer" "@semantic-release/release-notes-generator"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
